name: Solr Core Performance Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/solr-core-perf-test.yml'
      - 'solr/core/**'

jobs:
  test:
    name: Run Solr Core Perf Test

    runs-on: ubuntu-latest

    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}

    steps:
    # Setup
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 21
        java-package: jdk
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-solrj-${{ hashFiles('versions.lock') }}
        restore-keys: |
          ${{ runner.os }}-gradle-solrj-
          ${{ runner.os }}-gradle-
    - name: Test the Solr Cache Core Performance
      run: ./gradlew -Djavac.failOnWarnings=false test --tests org.apache.solr.search.TestSolrCachePerf
    - name: Test the Solr Search Core Performance
      run: ./gradlew -Djavac.failOnWarnings=false test --tests org.apache.solr.search.TestSearchPerf
    - name: Test the Solr Writer Core Performance
      run: ./gradlew -Djavac.failOnWarnings=false test --tests org.apache.solr.request.TestWriterPerf
    - name: Test the Solr Core Indexing Performance
      run: ./gradlew -Djavac.failOnWarnings=false test --tests org.apache.solr.update.TestIndexingPerformance
    - name: Test the Solr Core Configuration Loading Performance
      run: ./gradlew -Djavac.failOnWarnings=false test --tests org.apache.solr.core.TestConfLoadPerf
    - name: Test the SolrJ Performance
      run: ./gradlew -Djavac.failOnWarnings=false test --tests org.apache.solr.search.TestSolrJ
    - name: Test the Java Bin Codec Performance
      run: ./gradlew -Djavac.failOnWarnings=false test --tests org.apache.solr.common.util.TestJavaBinCodec