name: Solr Core Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/solr-core-test.yml'
      - 'solr/core/**'

jobs:
  test:
    name: Run Solr Core Tests

    runs-on: ubuntu-latest

    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}

    steps:
    # Setup
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 21
        java-package: jdk
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-solrj-${{ hashFiles('versions.lock') }}
        restore-keys: |
          ${{ runner.os }}-gradle-solrj-
          ${{ runner.os }}-gradle-
    - name: Test the Solr Core Package
      run: ./gradlew -Djavac.failOnWarnings=false -Dtests.useSecurityManager=false solr:core:test --fail-fast
